import type { Metadata, Viewport } from "next";
import { JetBrains_Mono, Bebas_Neue, Fira_Sans } from "next/font/google";
import "./globals.css";

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
}

// 1. JetBrains Mono
const jetbrainsMono = JetBrains_Mono({
  weight: '700',
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

// 2. Bebas Neue (Single weight font, explicit '400' required)
const bebasNeue = Bebas_Neue({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-display',
  display: 'swap',
});

// 3. Fira Sans
const firaSans = Fira_Sans({
  weight: ['300', '500', '700'],
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`
          h-full w-dw overflow-x-hidden antialiased
          `}
    >
      <body
        className={`
          ${jetbrainsMono.variable}
          ${bebasNeue.variable}
          ${firaSans.variable}
          `}
      >
        {children}
      </body>
    </html>
  );
}
