import type { Metadata } from "next";
import "./globals.css";
import FluidOverlay from "./components/fluid_overlay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FluidOverlay>
          {children}
        </FluidOverlay>
      </body>
    </html>
  );
}
